"""Fixed models v1.0.05

Revision ID: 2b2957699309
Revises: b757b7b44c84
Create Date: 2025-07-05 16:26:37.063070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b2957699309'
down_revision = 'b757b7b44c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('known_word', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uniqe_known_word_per_language'), type_='unique')
        batch_op.create_unique_constraint('unique_known_word_per_language', ['user_id', 'word', 'language'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('known_word', schema=None) as batch_op:
        batch_op.drop_constraint('unique_known_word_per_language', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uniqe_known_word_per_language'), ['user_id', 'word', 'language'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
