"""Increase password_hash length

Revision ID: 47babffc8e6c
Revises: 0aa130f298a9
Create Date: 2025-07-01 20:20:22.828822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47babffc8e6c'
down_revision = '0aa130f298a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
