"""Fixing Models

Revision ID: 585054ac64fb
Revises: 174e0db9602b
Create Date: 2025-07-04 11:41:14.645668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585054ac64fb'
down_revision = '174e0db9602b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
