"""Add language support to Meaning, KnownWord, Upload

Revision ID: 7bfa268555f2
Revises: 47babffc8e6c
Create Date: 2025-07-02 18:21:30.989732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfa268555f2'
down_revision = '47babffc8e6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('known_word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=False))

    with op.batch_alter_table('meaning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=False))

    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('meaning', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('known_word', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
