"""Fixed models v1.0.05

Revision ID: b757b7b44c84
Revises: 585054ac64fb
Create Date: 2025-07-05 16:25:43.209358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b757b7b44c84'
down_revision = '585054ac64fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('known_word', schema=None) as batch_op:
        batch_op.create_unique_constraint('uniqe_known_word_per_language', ['user_id', 'word', 'language'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('known_word', schema=None) as batch_op:
        batch_op.drop_constraint('uniqe_known_word_per_language', type_='unique')

    # ### end Alembic commands ###
